"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['Attendance_System.py']
DATA_FILES = ['attendance_report','data','database','photos','haarcascade_frontalface_alt.xml','classifier.xml','face_recognition.py']
OPTIONS = {}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
